name: Release macOS app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.1'
        channel: 'stable'
        architecture: x64
    - run: flutter build macos --release
    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'build/macos/Build/Products/Release/skyle_ik.app'
        token: ${{ secrets.RELEASES_TOKEN }}
