name: Release macOS app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.7'
        channel: 'stable'
        architecture: x64
        cache: true
    - run: flutter build macos --release --split-debug-info=build/macos/Build/Products/debug-info
    - run: mkdir build/macos/Build/Products/Release/skyle_ik-macos; cp -r build/macos/Build/Products/Release/skyle_ik.app build/macos/Build/Products/Release/skyle_ik-macos
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: skyle_ik-macos.zip
        directory: build/macos/Build/Products/Release/skyle_ik-macos

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'build/macos/Build/Products/Release/skyle_ik-macos/skyle_ik-macos.zip'
        token: ${{ secrets.RELEASES_TOKEN }}
        tag: '1.1.1'
        commit: main
        allowUpdates: true