name: Release Android app

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.3'
        channel: 'stable'
        cache: true
    - run: flutter build apk --release
    - run: flutter build appbundle --release

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: skyle_ik-android.zip
        directory: build/app/outputs/apk/release

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'build/app/outputs/apk/release/skyle_ik-android.zip'
        token: ${{ secrets.RELEASES_TOKEN }}
        tag: '1.0.0'
        commit: main
        allowUpdates: true