name: Release linux app

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.3'
        channel: 'stable'
        cache: true
    - name: Install dependencies
      run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-0 libblkid1 liblzma5 libgtk-3-dev liblzma-dev
    - run: flutter build linux --release

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: skyle_ik-linux.zip
        directory: build/linux/x64/release/bundle/

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'build/linux/x64/release/bundle/skyle_ik-linux.zip'
        token: ${{ secrets.RELEASES_TOKEN }}
        tag: '1.0.0'
        commit: main
        allowUpdates: true
