name: Release iPadOS app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.7'
        channel: 'stable'
        architecture: x64
        cache: true
    - run: flutter build ios --release --no-codesign
    - run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/SkyleIK.app

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: skyle_ik-ios.zip
        directory: build/ios/iphoneos

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'build/ios/iphoneos/skyle_ik-ios.zip'
        token: ${{ secrets.RELEASES_TOKEN }}
        tag: '1.1.1'
        commit: main
        allowUpdates: true